### ISSUE TITLE
security: ssl ca verification disabled

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/obs-service-download_files#19]
https://bugzilla.suse.com/show_bug.cgi?id=1053984

the wget call is done default with SSL verification disabled.

This should only be optional, and SSL verification should be default on.

(Just a small step for security.)

**Comment by adrianschroeter** [comment]
Done in commit 50fa599d0d947e460b5cd780ff4f25b078154e66, needs a bit more testing
