### ISSUE TITLE
"osc service localrun download_files" does not work in some projects

### ISSUE THREAD

**Issue by weberhofer** [openSUSE/obs-service-download_files#29]
I like the osc download-feature a lot, but it started to do nothing a while ago. E.g. Forking https://build.opensuse.org/package/show/X11:RemoteDesktop/remmina does no longer download the source files.
Using the verbose mode results in:
```
makeurl: https://api.opensuse.org ['source', 'home:weberho:branches:X11:RemoteDesktop', 'remmina'] cmd=getprojectservices
makeurl: https://api.opensuse.org ['person', 'weberho'] []
```
In other projects, the download works nicely, also with several source files in a package. What's wrong? Do you have an idea?

**Comment by marcus-h** [comment]
On 2021-02-03 07:41:21 -0800, Johannes Weberhofer wrote:
> I like the osc download-feature a lot, but it started to do nothing a while ago. E.g. Forking https://build.opensuse.org/package/show/X11:RemoteDesktop/remmina does no longer download the source files.
> Using the verbose mode results in:
> ```
> makeurl: https://api.opensuse.org ['source', 'home:weberho:branches:X11:RemoteDesktop', 'remmina'] cmd=getprojectservices
> makeurl: https://api.opensuse.org ['person', 'weberho'] []
> ```
> In other projects, the download works nicely, also with several source files in a package. What's wrong? Do you have an idea?
>
The download_files service, which comes from the openSUSE:Factory project,
has mode=disabled and "localrun" does not execute disabled services anymore.
For the details see [1].

[1] https://github.com/openSUSE/osc/issues/874

**Comment by weberhofer** [comment]
Thank you for that fast response. That's is a strange behavior, but if one knows, it works :-)
