### ISSUE TITLE
Warn when downloading files over http and ftp

### ISSUE THREAD

**Issue by msmeissn** [openSUSE/obs-service-download_files#39]
http: is no longer considered secure, can you disallow download_files from http and ftp urls?

same for ftp

Goal is for maintainers to switch to https URLs.

@jsegitz

**Comment by coolo** [comment]
IMO: That sounds like a policy to be coded elsewhere (rpmlint?). This is a download service not a policy checker

**Comment by dirkmueller** [comment]
Go for fixing it first:

```
git grep -E "Source.*(http|ftp)://" | wc -l
2913
```

**Comment by dirkmueller** [comment]
Also there are many open source components in our distro that are not available via https:// for example, so people would be removing the canonical url to fix the error instead, which is even counter productive for our Supply Chain Security project.

**Comment by dirkmueller** [comment]
also problematic (and not done via obs-source-download_files): 

```
git grep -E "url.*git://" | grep -v Git-Clone | wc -l
271
```

**Comment by msmeissn** [comment]
my idea is having a WARN algorithm to have maintainers go look for https urls.

I know the state of the distribution, but i cant do this all myself.

**Comment by jsegitz** [comment]
I would also favor a warning to make packagers aware. Disallowing it fully will be inconvinient for ancient projects that don't offer anything. 

As for rpmlint: First of all that's rather late. When this service is run (quite often directly by the maintainer) I think the chances are higher that he will take the chance to do the change. Also I'm not sure if this information even is in the resulting binary rpm.

**Comment by jsegitz** [comment]
Okay, I'm convinced :) I'll add this to our improvement topics and we'll explore the possibility to have that in rpmlint. That seems to be the logical place to me given the reasoning above
