### ISSUE TITLE
download files should download Patch entries.

### ISSUE THREAD

**Issue by cfelder** [openSUSE/obs-service-download_files#6]
It would be nice if this service could also download Patch: and Patch%d: entries, e.g.:

    Patch:                 %{baseurl}/%{kname}-%{version}.from-%{baseversion}.patch

or

    Patch1:                 %{baseurl}/%{kname}-%{version}.from-%{baseversion}.patch

**Comment by cfelder** [comment]
At the moment I use an extra Source line as workaround.

**Comment by M0ses** [comment]
sounds reasonable - as I`m already doing some fixes - I will take care of it

**Comment by cfelder** [comment]
Thank you very much :-)
